run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - typecheck
    - unused
    - errcheck
    - gosimple
    - gofmt

output:
  format: colored-line-number
